### ISSUE TITLE
Demos?

### ISSUE THREAD

**Issue by austinkregel** [codefocus/vernacular#1]
I was wondering if you had any kind of a demo set up for Vernacular. It's be nice to see it in action

**Comment by codefocus** [comment]
Hey Austin, this repo was just the first few lines of something that has been on the back burner for well over a year now, so there's no demo or even a functional library.

However, I've started work on this again, and will push something useful to github shortly ;)

**Comment by austinkregel** [comment]
Yea upon reviewing issues that I've posted in the past, I saw this and that it was still open. I looked over the repo and realized it didn't seem to have taken off. 

I am really interested in the topic and NLP for php, just can't invest time into it personally right now. I'm really looking forward to seeing this package grow into a great PHP-NLP library. :) 

I don't mean to rush you or anything, I just figured there's not much of a point in having this issue open :3
